version: '3.8'

services:
  accounts:
    image: '${DOCKER_REGISTRY}subgraph-accounts${DOCKER_TAG}'
    container_name: accounts
    networks:
      - test
    ports:
      - "0.0.0.0:4001:4001"
    environment:
      PORT: 4001
      SUBGRAPH_DELAY_MS: ${SUBGRAPH_DELAY_MS}
    healthcheck:
        test: ["CMD", "/usr/lib/apt/apt-helper", "download-file", "http://0.0.0.0:4001/graphql", "temp"]
        interval: 3s
        timeout: 5s
        retries: 10
  inventory:
    image: '${DOCKER_REGISTRY}subgraph-inventory${DOCKER_TAG}'
    container_name: inventory
    networks:
      - test
    ports:
      - 4002:4002
    environment:
      PORT: 4002
      SUBGRAPH_DELAY_MS: ${SUBGRAPH_DELAY_MS}
    healthcheck:
        test: ["CMD", "/usr/lib/apt/apt-helper", "download-file", "http://0.0.0.0:4002/graphql", "temp"]
        interval: 3s
        timeout: 5s
        retries: 10
  products:
    image: '${DOCKER_REGISTRY}subgraph-products${DOCKER_TAG}'
    container_name: products
    networks:
      - test
    ports:
      - "0.0.0.0:4003:4003"
    environment:
      PORT: 4003
      SUBGRAPH_DELAY_MS: ${SUBGRAPH_DELAY_MS}
    healthcheck:
      test: ["CMD", "/usr/lib/apt/apt-helper", "download-file", "http://0.0.0.0:4003/graphql", "temp"]
      interval: 3s
      timeout: 5s
      retries: 10
  reviews:
    image: '${DOCKER_REGISTRY}subgraph-reviews${DOCKER_TAG}'
    container_name: reviews
    networks:
      - test
    ports:
      - 4004:4004
    environment:
      PORT: 4004
      SUBGRAPH_DELAY_MS: ${SUBGRAPH_DELAY_MS}
    healthcheck:
        test: ["CMD", "/usr/lib/apt/apt-helper", "download-file", "http://0.0.0.0:4004/graphql", "temp"]
        interval: 3s
        timeout: 5s
        retries: 10
        
networks:
  test:
    name: test
