version: '3.8'

services:
  gateway:
    image: gateway/apollo-gateway-with-yoga-uws
    container_name: gateway
    networks:
      - test
    ports:
      - 4000:4000
    environment:
      PORT: 4000
    build:
      context: ${BASE_DIR:-.}/apollo-gateway-with-yoga-uws
      dockerfile: ./Dockerfile
    depends_on:
      accounts: 
        condition: service_healthy
      inventory:
        condition: service_healthy
      products:
        condition: service_healthy
      reviews:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "-X", "POST", "-H" ,"Content-type: application/json", "http://localhost:4000/graphql", "--data-raw", "{\"query\": \"query { __typename }\"}"]
        interval: 3s
        timeout: 5s
        retries: 10
    mem_limit: "3g"
    mem_reservation: "1024m"
    cpus: "2"
    cpuset: "2"
networks:
  test:
    name: test