server:
  port: 4000
  host: 0.0.0.0

logger:
  level: error

sources:
  - id: gateways-benchmark
    type: federation
    config:
      supergraph:
        file: /dist/schema/local.graphql

endpoints:
  - path: /graphql
    from: gateways-benchmark
