on:
  workflow_call:
    inputs:
      hcl:
        type: string
        required: true
      dir:
        type: string
        required: true
      target:
        type: string
        required: true

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure eqemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'linux/arm64,linux/amd64'

      - name: configure docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build docker images
        timeout-minutes: 20
        id: docker-bake
        uses: docker/bake-action@v3
        env:
          DOCKER_REGISTRY: ghcr.io/${{ github.repository }}/
          COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
        with:
          workdir: ${{ inputs.dir }}
          provenance: false
          push: true
          files: ${{ inputs.hcl }}
          targets: ${{ inputs.target }}
          set: |
            *.cache-from=type=gha,scope=build
            *.cache-to=type=gha,scope=build,mode=max