name: ramping-vus
on:
  pull_request: {}
  push:
    branches:
      - 'main'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.step1.outputs.runner }}
    steps:
      - name: decide on runner
        id: step1
        run: |
          # if [ ${{ github.event_name == 'pull_request' }} ]; then
            # echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
          # else
            echo 'runner={"group": "benchmark-runners"}' >> $GITHUB_OUTPUT
          # fi

  benchmark:
    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        directory: [mesh, apollo-server, apollo-gateway-with-yoga, apollo-router, mercurius, wundergraph, stitching-federation-with-yoga, stitching-federation-with-yoga-deno, stitching-federation-with-yoga-bun]
    uses: ./.github/workflows/constant-vus-over-time.template.yaml
    name: ${{ matrix.directory }}
    with:
      gateway: ${{ matrix.directory }}
      vu: 1000
      time: 60s
      scenarioDir: scenarios/ramping-vus
      runner: ${{ needs.setup.outputs.runner }}

  report:
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: download artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: install dependencies
        run: yarn install
        working-directory: scenarios/ramping-vus

      - name: generate report
        run: yarn generate-report ${{ steps.download.outputs.download-path }} 
        working-directory: scenarios/ramping-vus
        env:
          CF_IMAGES_LINK: ${{ secrets.CF_IMAGES_LINK }}
          CF_IMAGES_TOKEN: ${{ secrets.CF_IMAGES_TOKEN }}

      - name: publish report
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: ramping-vus
          path: scenarios/ramping-vus/result.md
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}

      - name: copy report
        if: github.event_name == 'push'
        run: |
          cp scenarios/ramping-vus/result.md scenarios/ramping-vus/README.md

      - name: publish report
        uses: EndBug/add-and-commit@v9
        if: github.event_name == 'push'
        with:
          add: scenarios/ramping-vus/README.md
          message: 'Update results for scenario: ramping-vus'
          pull: '--rebase --autostash'
