on:
  workflow_call:
    inputs:
      scenarioDir:
        type: string
        required: true

jobs:
  report:
    runs-on: ubuntu-latest
    name: report for ${{ inputs.scenarioDir }} 
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: download artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: install dependencies
        run: yarn install
        working-directory: ${{ inputs.scenarioDir }}

      - name: generate report
        run: yarn generate-report ${{ steps.download.outputs.download-path }} 
        working-directory: ${{ inputs.scenarioDir }}
        env:
          SCENARIO_TITLE: ${{ inputs.scenarioDir }}
          CF_IMAGES_LINK: ${{ secrets.CF_IMAGES_LINK }}
          CF_IMAGES_TOKEN: ${{ secrets.CF_IMAGES_TOKEN }}

      - name: publish report (pull_request)
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: ${{ inputs.scenarioDir }}
          path: ${{ inputs.scenarioDir }}/result.md
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}

      - name: copy report (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cp ${{ inputs.scenarioDir }}/result.md ${{ inputs.scenarioDir }}/README.md

      - name: publish report (workflow_dispatch)
        uses: EndBug/add-and-commit@v9
        if: github.event_name == 'workflow_dispatch'
        with:
          add: ${{ inputs.scenarioDir }}/README.md
          message: 'Update results for scenario: ${{ inputs.scenarioDir }}'
          pull: '--rebase --autostash'